---
title: "SDiDの対照群ウェイト表"
author: "Ayumu Tanaka"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
---

```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,     # コードを表示
  message = FALSE, # パッケージ読込時などのメッセージを表示しない
  warning = FALSE  # 警告メッセージを表示しない
)
```

```{r table}
library(rio)
library(dplyr)
library(kableExtra)

# データの読み込み
aff <- rio::import("../../03_data_output/synthdid_control_weight_affiliate_country.dta")
ent <- rio::import("../../03_data_output/synthdid_control_weight_entry_country.dta")

# 国名で結合
tab <- full_join(
  aff[, c("country_name", "weight")],
  ent[, c("country_name", "weight")],
  by = "country_name",
  suffix = c("_aff", "_ent")
) %>%
  arrange(country_name) %>%
  rename(Country = country_name,
         Exit    = weight_aff,
         Entry   = weight_ent)

# LaTeX表の出力
tab %>%
  kable(format   = "latex",
        digits   = 4,
        align    = c("l", "r", "r"),
        booktabs = TRUE,
        caption  = "Synthetic DiD Control Unit Weights by Country",
        label    = "sdid_weights") %>%
  kable_styling(latex_options = c("hold_position")) %>%
  save_kable("../../04_tex/main/TabD3.tex")
```
